FROM golang:1.23.3 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o scheduler ./cmd/schedulegametrackers

FROM gcr.io/distroless/static

WORKDIR /

COPY --from=builder /app/scheduler .

CMD ["/scheduler"]
