FROM golang:1.23.3 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/watchgameupdates

FROM gcr.io/distroless/static

WORKDIR /
COPY --from=builder /app/main .

CMD ["/main", "-mode=worker"]
